import Group27 from '../../assets/01-shutterstock_476340928-Irina-Bg 1-1.png';
import USA from '../../assets/download 1.png';

export const influencersData = [
  {
    name: '@Zoesennett',
    description: 'Skin And beauty care',
    followers: '2.3M',
    imageSrc: Group27,
    price: '1',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '2',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@makaylaj2019',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '3',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@Angelian',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '4',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '5',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '6',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '7',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '8',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '9',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '10',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '11',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '12',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '13',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '14',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '15',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '16',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '2.3M',
    imageSrc: Group27,
    price: '17',
    flag: USA,
    nation: 'United States',
    friends: '186.8k',
    likes: '1.9M',
  },
];