import Image1 from '../../assets/images1.png';
import Image2 from '../../assets/images2.png';
import Image3 from '../../assets/images3.png';
import Image4 from '../../assets/images4.png';
import Image5 from '../../assets/images5.png';
import USA from '../../assets/download 1.png';

export const influencersData = [
  {
    name: '@Angelian',
    description: 'Skin And beauty care',
    followers: '2.3M',
    imageSrc: Image1,
    price: '500',
    flag: USA,
    nation: 'United States',
    friends: '286.8k',
    likes: '3.5M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '1.5M',
    imageSrc: Image2,
    price: '350',
    flag: USA,
    nation: 'United States',
    friends: '106.8k',
    likes: '1.9M',
  },
  {
    name: '@makaylaj2019',
    description: 'Music',
    followers: '3.7M',
    imageSrc: Image3,
    price: '425',
    flag: USA,
    nation: 'United States',
    friends: '286.8k',
    likes: '2M',
  },
  {
    name: '@Jack',
    description: 'Writer',
    followers: '975k',
    imageSrc: Image4,
    price: '150',
    flag: USA,
    nation: 'United States',
    friends: '86.8k',
    likes: '1M',
  },
  {
    name: '@Sara',
    description: 'Skin And beauty care',
    followers: '6.1M',
    imageSrc: Image5,
    price: '700',
    flag: USA,
    nation: 'United States',
    friends: '386.8k',
    likes: '4.5M',
  },
  {
    name: '@Angelian',
    description: 'Skin And beauty care',
    followers: '2.3M',
    imageSrc: Image1,
    price: '500',
    flag: USA,
    nation: 'United States',
    friends: '286.8k',
    likes: '3.5M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '1.5M',
    imageSrc: Image2,
    price: '350',
    flag: USA,
    nation: 'United States',
    friends: '106.8k',
    likes: '1.9M',
  },
  {
    name: '@makaylaj2019',
    description: 'Music',
    followers: '3.7M',
    imageSrc: Image3,
    price: '425',
    flag: USA,
    nation: 'United States',
    friends: '286.8k',
    likes: '2M',
  },
  {
    name: '@Jack',
    description: 'Writer',
    followers: '975k',
    imageSrc: Image4,
    price: '150',
    flag: USA,
    nation: 'United States',
    friends: '86.8k',
    likes: '1M',
  },
  {
    name: '@Sara',
    description: 'Skin And beauty care',
    followers: '6.1M',
    imageSrc: Image5,
    price: '700',
    flag: USA,
    nation: 'United States',
    friends: '386.8k',
    likes: '4.5M',
  },
  {
    name: '@Angelian',
    description: 'Skin And beauty care',
    followers: '2.3M',
    imageSrc: Image1,
    price: '500',
    flag: USA,
    nation: 'United States',
    friends: '286.8k',
    likes: '3.5M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '1.5M',
    imageSrc: Image2,
    price: '350',
    flag: USA,
    nation: 'United States',
    friends: '106.8k',
    likes: '1.9M',
  },
  {
    name: '@makaylaj2019',
    description: 'Music',
    followers: '3.7M',
    imageSrc: Image3,
    price: '425',
    flag: USA,
    nation: 'United States',
    friends: '286.8k',
    likes: '2M',
  },
  {
    name: '@Jack',
    description: 'Writer',
    followers: '975k',
    imageSrc: Image4,
    price: '150',
    flag: USA,
    nation: 'United States',
    friends: '86.8k',
    likes: '1M',
  },
  {
    name: '@Sara',
    description: 'Skin And beauty care',
    followers: '6.1M',
    imageSrc: Image5,
    price: '700',
    flag: USA,
    nation: 'United States',
    friends: '386.8k',
    likes: '4.5M',
  },
  {
    name: '@Angelian',
    description: 'Skin And beauty care',
    followers: '2.3M',
    imageSrc: Image1,
    price: '500',
    flag: USA,
    nation: 'United States',
    friends: '286.8k',
    likes: '3.5M',
  },
  {
    name: '@AllisonCamile',
    description: 'Writer',
    followers: '1.5M',
    imageSrc: Image2,
    price: '350',
    flag: USA,
    nation: 'United States',
    friends: '106.8k',
    likes: '1.9M',
  },
];